import api from "@/lib/api";

/**
 * LexTracker Document Service
 * Purpose: Manages the transmission of legal evidence between the
 * Next.js frontend and the Spring Boot "Vault".
 */

// --- Interfaces ---

export interface CaseDocument {
  id: number;
  fileName: string;
  sourceOrigin: string;
  fileHash: string; // The SHA-256 Fingerprint generated by the Vault
  contentType: string;
  uploadDate?: string;
}

// --- Service Methods ---

/**
 * Uploads a physical file and initiates the Digital Chain of Custody.
 */
export const uploadEvidence = async (
  caseId: number,
  file: File,
  sourceOrigin: string,
): Promise<CaseDocument> => {
  const formData = new FormData();
  formData.append("file", file);
  formData.append("sourceOrigin", sourceOrigin);

  try {
    const response = await api.post<CaseDocument>(
      `/api/documents/upload/${caseId}`,
      formData,
      {
        // Do NOT set Content-Type - Axios + browser will add correct multipart boundary
      },
    );

    console.log(
      "🛡️ Integrity Engine: File certified and hashed successfully.",
      response.data,
    );
    return response.data;
  } catch (error: any) {
    console.error(
      "⚖️ LexTracker Service Error: Chain of custody interrupted during upload.",
      error,
    );
    throw error;
  }
};

/**
 * Retrieves the complete list of certified evidence for a specific case.
 */
export const getCaseDocuments = async (
  caseId: number,
): Promise<CaseDocument[]> => {
  try {
    const response = await api.get<CaseDocument[]>(
      `/api/documents/case/${caseId}`,
    );
    return Array.isArray(response.data) ? response.data : [];
  } catch (error) {
    console.error(
      `Vault Access Error: Could not retrieve documents for Case #${caseId}`,
      error,
    );
    return [];
  }
};

/**
 * Generates a secure download URL for a specific document.
 */
export const getDocumentDownloadUrl = (docId: number): string => {
  const baseUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080";
  const sanitizedBase = baseUrl.endsWith("/") ? baseUrl.slice(0, -1) : baseUrl;
  return `${sanitizedBase}/api/documents/download/${docId}`;
};
